# Generated by Django 3.2.7 on 2021-11-03 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BillBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billboard', models.CharField(max_length=200)),
                ('place', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SongName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SongType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_type', models.CharField(max_length=200)),
            ],
        ),
    ]
